### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by sindresorhus** [mukeshsoni/screencapturekit-node#2]
https://github.com/mukeshsoni/screencapturekit-node/blob/main/Sources/screencapturekit-cli/Utilities.swift is a direct copy of https://github.com/wulkano/aperture-node/blob/main/Sources/ApertureCLI/Utilities.swift, but the license is not preserved.

**Comment by mukeshsoni** [comment]
Sorry about that. Have added the license. @sindresorhus
